services:
  musclerpg:
    build: .
    container_name: musclerpg_app
    network_mode: host
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
