services:
  musclerpg:
    build: .
    container_name: musclerpg_app
    ports:
      - "8502:8502"
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped